import React from 'react';
import { Sprout, Factory, CheckCircle2, AlertTriangle, ShieldCheck, Printer, ArrowRight, DollarSign } from 'lucide-react';

export default function FarmerIndustryCard({ result }) {
  if (!result) return null;

  const isHealthy = result.prediction === 'HEALTHY';
  const grade = result.quality_grade || 'C';
  const yieldData = result.yield_analysis || {};

  const farmerPrice = isHealthy
    ? (grade === 'A' ? '₹16.50 – ₹18.00' : '₹13.00 – ₹15.50')
    : '₹2.00 – ₹4.00 (Salvage/Industrial)';

  const farmerAction = isHealthy
    ? (grade === 'A' ? 'Premium Batch — Ready for Export & Direct Retail' : 'Good Quality — Suitable for Local Milling & Processing')
    : 'DISCARD / SEPARATE IMMEDIATELY — High Fungal Risk';

  const industryMillingGrade = isHealthy
    ? (grade === 'A' ? 'Class I Premium Milling Grade (ISO 5517)' : 'Class II Commercial Grade')
    : 'Class III Rejected Batch — Non-Edible Grade';

  const handlePrintCertificate = () => {
    const printWindow = window.open('', '_blank');
    printWindow.document.write(`
      <html>
        <head>
          <title>Coconut AI Quality Certificate - ${result.prediction_id || 'SCAN'}</title>
          <style>
            body { font-family: 'Helvetica Neue', Arial, sans-serif; padding: 40px; color: #0f172a; }
            .header { border-bottom: 3px solid #059669; padding-bottom: 16px; margin-bottom: 24px; display: flex; justify-content: space-between; }
            .title { font-size: 24px; font-weight: bold; color: #064e3b; }
            .badge { display: inline-block; padding: 6px 16px; border-radius: 20px; font-weight: bold; color: white; background-color: ${isHealthy ? '#059669' : '#dc2626'}; }
            .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin: 24px 0; }
            .box { background: #f8fafc; border: 1px solid #e2e8f0; padding: 16px; border-radius: 8px; }
            .label { font-size: 12px; color: #64748b; font-weight: bold; text-transform: uppercase; }
            .value { font-size: 20px; font-weight: bold; color: #0f172a; margin-top: 4px; }
            .footer { margin-top: 40px; border-top: 1px solid #e2e8f0; padding-top: 16px; font-size: 12px; color: #64748b; text-align: center; }
          </style>
        </head>
        <body>
          <div class="header">
            <div>
              <div class="title">🥥 Coconut AI — Official Quality Certificate</div>
              <div style="font-size: 13px; color: #059669;">Automated Agricultural & Industrial Inspection Report</div>
            </div>
            <div>
              <span class="badge">${result.prediction} — GRADE ${grade}</span>
            </div>
          </div>

          <div class="grid">
            <div class="box">
              <div class="label">Sample Classification</div>
              <div class="value">${result.prediction} (${result.confidence?.toFixed(1)}% Confidence)</div>
            </div>
            <div class="box">
              <div class="label">Quality Grade</div>
              <div class="value">Grade ${grade} (${result.quality_grade_label || 'Standard'})</div>
            </div>
            <div class="box">
              <div class="label">Usable Copra Weight</div>
              <div class="value">${yieldData.usable_copra_weight_g || 120} grams</div>
            </div>
            <div class="box">
              <div class="label">Oil Extraction Potential</div>
              <div class="value">${yieldData.oil_extraction_pct || 60}% Potential</div>
            </div>
          </div>

          <div class="box" style="margin-bottom: 20px;">
            <div class="label">Industry Commercial Classification</div>
            <div class="value" style="font-size: 16px;">${industryMillingGrade}</div>
          </div>

          <div class="box">
            <div class="label">Farmer Farm-Gate Recommendation</div>
            <div class="value" style="font-size: 15px; color: ${isHealthy ? '#059669' : '#dc2626'};">${farmerAction}</div>
          </div>

          <div class="footer">
            Generated by Coconut AI Assessment Engine • MobileNetV2 Deep Learning & Grad-CAM • Certified Inspection
          </div>
          <script>window.print();</script>
        </body>
      </html>
    `);
    printWindow.document.close();
  };

  return (
    <div className="card animate-fade-in" style={{ borderLeft: `6px solid ${isHealthy ? '#10b981' : '#ef4444'}` }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '18px', flexWrap: 'wrap', gap: '12px' }}>
        <div className="card-title" style={{ margin: 0 }}>
          <ShieldCheck size={22} color="#059669" />
          <span>Farmer & Industry Commercial Decision Support</span>
        </div>
        <button
          onClick={handlePrintCertificate}
          className="btn btn-secondary"
          style={{ padding: '6px 14px', fontSize: '13px', backgroundColor: '#ecfdf5', color: '#064e3b', borderColor: '#a7f3d0' }}
        >
          <Printer size={15} />
          <span>Print Quality Certificate</span>
        </button>
      </div>

      <div className="grid-2">
        {/* Farmer Panel */}
        <div style={{ backgroundColor: '#f0fdf4', border: '1px solid #bbf7d0', borderRadius: '14px', padding: '18px' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '12px' }}>
            <Sprout size={20} color="#047857" />
            <h4 style={{ margin: 0, fontSize: '16px', fontWeight: 700, color: '#064e3b' }}>👨‍🌾 Farmer Advisory (Farm-Gate)</h4>
          </div>

          <div style={{ marginBottom: '10px' }}>
            <div style={{ fontSize: '12px', color: '#047857', fontWeight: 700, textTransform: 'uppercase' }}>Recommended Market Action</div>
            <div style={{ fontSize: '14px', fontWeight: 800, color: isHealthy ? '#064e3b' : '#dc2626', marginTop: '2px' }}>
              {farmerAction}
            </div>
          </div>

          <div style={{ marginBottom: '12px', backgroundColor: '#ffffff', padding: '10px 14px', borderRadius: '10px', border: '1px solid #d1fae5' }}>
            <div style={{ fontSize: '12px', color: '#64748b', fontWeight: 600 }}>Estimated Farm-Gate Value</div>
            <div style={{ fontSize: '18px', fontWeight: 800, color: isHealthy ? '#059669' : '#dc2626' }}>
              {farmerPrice} <span style={{ fontSize: '12px', fontWeight: 500, color: '#64748b' }}>per coconut nut</span>
            </div>
          </div>

          <div style={{ fontSize: '12px', color: '#374151', lineHeight: '1.5' }}>
            <strong>Action Steps:</strong>
            <ul style={{ margin: '4px 0 0 16px', padding: 0 }}>
              {isHealthy ? (
                <>
                  <li>Keep in well-ventilated dry storage (Humidity &lt; 65%).</li>
                  <li>Ideal for immediate sale to commercial copra processors.</li>
                </>
              ) : (
                <>
                  <li>Isolate this batch immediately to prevent fungal spore spread.</li>
                  <li>Sun-dry kernel to reduce surface moisture below 6%.</li>
                </>
              )}
            </ul>
          </div>
        </div>

        {/* Industry Manager Panel */}
        <div style={{ backgroundColor: '#f8fafc', border: '1px solid #e2e8f0', borderRadius: '14px', padding: '18px' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '12px' }}>
            <Factory size={20} color="#0284c7" />
            <h4 style={{ margin: 0, fontSize: '16px', fontWeight: 700, color: '#0f172a' }}>🏭 Industry & Milling Rating</h4>
          </div>

          <div style={{ marginBottom: '10px' }}>
            <div style={{ fontSize: '12px', color: '#64748b', fontWeight: 700, textTransform: 'uppercase' }}>Commercial Grade Standard</div>
            <div style={{ fontSize: '14px', fontWeight: 800, color: '#0f172a', marginTop: '2px' }}>
              {industryMillingGrade}
            </div>
          </div>

          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '10px', marginBottom: '12px' }}>
            <div style={{ backgroundColor: '#ffffff', padding: '10px', borderRadius: '10px', border: '1px solid #e2e8f0' }}>
              <div style={{ fontSize: '11px', color: '#64748b', fontWeight: 600 }}>Usable Copra</div>
              <div style={{ fontSize: '16px', fontWeight: 800, color: '#0f172a' }}>{yieldData.usable_copra_weight_g || 120}g</div>
            </div>
            <div style={{ backgroundColor: '#ffffff', padding: '10px', borderRadius: '10px', border: '1px solid #e2e8f0' }}>
              <div style={{ fontSize: '11px', color: '#64748b', fontWeight: 600 }}>Oil Content</div>
              <div style={{ fontSize: '16px', fontWeight: 800, color: '#0284c7' }}>{yieldData.oil_extraction_pct || 60}%</div>
            </div>
          </div>

          <div style={{ fontSize: '12px', color: '#475569', lineHeight: '1.5' }}>
            <strong>Warehouse Protocol:</strong>
            <div style={{ marginTop: '2px' }}>
              {isHealthy ? '✅ Approved for high-grade oil extraction and desiccated coconut production.' : '❌ Replaced from edible oil stream. Direct to industrial soap/bio-fuel processing.'}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
